spring:  
  application:
    name: users-ws
  cloud:
    consul:
      host: localhost
      port: 8500
  output.ansi.enabled: ALWAYS
  
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  data:
    mongodb:
      database: AdminDashboard
      port: 27017
      host: localhost

